name: dnt
description: A sample command-line application.
version: 1.0.0
environment:
  sdk: ^3.2.6
dependencies:
  shelf: 1.4.1
  shelf_static: 1.0.0
  shelf_router: 1.1.4
  shelf_cors_headers: 0.1.5
  dotenv: 4.2.0